### ISSUE TITLE
Incompatibility with "Better with Graves" mod

### ISSUE THREAD

**Issue by Zano1999** [average-bread/morefeatures#2]
Incompatible with that mod: https://github.com/CitizenFoffie/BTAGraves

The game crash on startup with this error:

java.lang.IllegalArgumentException: Slot 2000 is already occupied by tile.btacfgraves.grave when adding vanilla.colored.glowstone
	at net.minecraft.core.block.Block.handler$zdc000$halplibe$addInfo(Block.java:1568)
	at net.minecraft.core.block.Block.<init>(Block.java:65)
	at cursedbread.morefeatures.blocks.VanilaBlockColoredGlowstone.<init>(VanilaBlockColoredGlowstone.java:20)
	at cursedbread.morefeatures.FeaturesMain.beforeGameStart(FeaturesMain.java:125)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.client.Minecraft.handler$zdg000$halplibe$beforeGameStartEntrypoint(Minecraft.java:2442)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java)
	at net.minecraft.client.Minecraft.run(Minecraft.java:738)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Bigjango13** [comment]
This is an ID overlap, and can be fixed in the config of either mod. Regardless, this should be fixed with my latest PR to the graves mod.
